export type TemplateLayoutType =
  | 'cinelove_movie'
  | 'zenlove_minimal'
  | 'chungdoi_traditional'
  | 'chungdoi_magazine'
  | 'botanical_garden'
  | 'full_long_card';

export interface TemplateColorVariant {
  id: string;
  name: string;
  primaryColor: string;
  accentColor: string;
  frameAsset: string;
  bgTexture?: string;
}

export interface TemplateConfig {
  id: string;
  name: string;
  category: 'truyen_thong' | 'hien_dai' | 'hoa_la' | 'toi_gian';
  source: 'chungdoi' | 'zenlove' | 'cinelove' | 'motdoi';
  layoutType: TemplateLayoutType;
  primaryColor: string;
  accentColor: string;
  bgTexture: string;
  cardBg: string;
  envelopeGradient: string;
  sealSymbol: string;
  frameAsset: string;
  description: string;
  tag: string;
  isLongThumbnail?: boolean;
  colorVariants?: TemplateColorVariant[];
}

export const TEMPLATES: TemplateConfig[] = [
  {
    "id": "cine-thiep-cuoi-61",
    "name": "Điện Ảnh Hiện Đại 01",
    "category": "hien_dai",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#1c1917",
    "accentColor": "#eab308",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-61.webp",
    "description": "Mẫu thiệp cưới điện ảnh Điện Ảnh Hiện Đại 61 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Hot Trend",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-39",
    "name": "Art Deco Hoàng Kim 02",
    "category": "hien_dai",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#0f172a",
    "accentColor": "#38bdf8",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-39.webp",
    "description": "Mẫu thiệp cưới điện ảnh Art Deco Sang Trọng 39 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Nổi bật",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-44",
    "name": "Hollywood Lãng Mạn 03",
    "category": "hien_dai",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#831843",
    "accentColor": "#f472b6",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-44.webp",
    "description": "Mẫu thiệp cưới điện ảnh Hollywood Lãng Mạn 44 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Đặc sắc",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-47",
    "name": "Thảm Đỏ Premiere 04",
    "category": "hien_dai",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#991b1b",
    "accentColor": "#fbbf24",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-47.webp",
    "description": "Mẫu thiệp cưới điện ảnh Thảm Đỏ Premiere 47 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Mới 2026",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-42",
    "name": "Thanh Xuân Ngọt Ngào 05",
    "category": "toi_gian",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#431407",
    "accentColor": "#fb923c",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-42.webp",
    "description": "Mẫu thiệp cưới điện ảnh Thanh Xuân Ngọt Ngào 42 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Yêu thích",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-2",
    "name": "Lookbook Thời Trang 06",
    "category": "hien_dai",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#18181b",
    "accentColor": "#e4e4e7",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-2.webp",
    "description": "Mẫu thiệp cưới điện ảnh Lookbook Tạp Chí 02 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Vogue",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-38",
    "name": "Cổ Điển Thơ Mộng 07",
    "category": "toi_gian",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#3f3f46",
    "accentColor": "#a1a1aa",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-38.webp",
    "description": "Mẫu thiệp cưới điện ảnh Cổ Điển Thơ Mộng 38 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Vintage",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-46",
    "name": "Thước Phim Hạnh Phúc 08",
    "category": "hien_dai",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#172554",
    "accentColor": "#60a5fa",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-46.webp",
    "description": "Mẫu thiệp cưới điện ảnh Phim Tài Liệu Tình Yêu 46 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Classic",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-1",
    "name": "Golden Cinema Hoàng Gia 09",
    "category": "hien_dai",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#78350f",
    "accentColor": "#fbbf24",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-1.webp",
    "description": "Mẫu thiệp cưới điện ảnh Golden Cinema 01 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "VIP",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-36",
    "name": "Nhật Ký Tình Yêu 10",
    "category": "toi_gian",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#27272a",
    "accentColor": "#d4d4d8",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-36.webp",
    "description": "Mẫu thiệp cưới điện ảnh Nhật Ký Đôi Ta 36 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Thanh lịch",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-114",
    "name": "Boarding Pass - Vé Bay Hạnh Phúc 11",
    "category": "hien_dai",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#0c4a6e",
    "accentColor": "#38bdf8",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-114.webp",
    "description": "Mẫu thiệp cưới điện ảnh Boarding Pass Độc Đáo 114 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Độc quyền",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-40",
    "name": "Khung Phim 35mm Vintage 12",
    "category": "hien_dai",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#18181b",
    "accentColor": "#f59e0b",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-40.webp",
    "description": "Mẫu thiệp cưới điện ảnh Khung Phim 35mm 40 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Filmstrip",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-16",
    "name": "Khoảnh Khắc Kỷ Niệm 13",
    "category": "toi_gian",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#52525b",
    "accentColor": "#cbd5e1",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-16.webp",
    "description": "Mẫu thiệp cưới điện ảnh Polaroid Kỷ Niệm 16 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Nhẹ nhàng",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-48",
    "name": "Dạ Tiệc Trọng Đại 14",
    "category": "hien_dai",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#701a75",
    "accentColor": "#f472b6",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-48.webp",
    "description": "Mẫu thiệp cưới điện ảnh Đêm Gala Trọng Đại 48 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Sang trọng",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-19",
    "name": "Letterpress Tinh Khôi 15",
    "category": "toi_gian",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#44403c",
    "accentColor": "#d6d3d1",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-19.webp",
    "description": "Mẫu thiệp cưới điện ảnh Letterpress Tối Giản 19 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Mộc mạc",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-56",
    "name": "Indie Love Story 16",
    "category": "hien_dai",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#1c1917",
    "accentColor": "#a8a29e",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-56.webp",
    "description": "Mẫu thiệp cưới điện ảnh Indie Love Story 56 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Phim ngắn",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-tone-xanh",
    "name": "Xanh Mint Dịu Mát 17",
    "category": "hoa_la",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#065f46",
    "accentColor": "#34d399",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-tone-xanh.webp",
    "description": "Mẫu thiệp cưới điện ảnh Tone Xanh Mint Tươi Mát thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Tone Mint",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-53",
    "name": "Hoàng Hôn Tình Nồng 18",
    "category": "hien_dai",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#9a3412",
    "accentColor": "#fdba74",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-53.webp",
    "description": "Mẫu thiệp cưới điện ảnh Sunset Romance 53 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Hoàng hôn",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-5",
    "name": "Movie Ticket - Vé Phim Tình Yêu 19",
    "category": "hien_dai",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#881337",
    "accentColor": "#fb7185",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-5.webp",
    "description": "Mẫu thiệp cưới điện ảnh Movie Ticket Rạp Cưới 05 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Vé xem phim",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-23",
    "name": "Biển Xanh Lãng Mạn 20",
    "category": "hoa_la",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#0369a1",
    "accentColor": "#38bdf8",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-23.webp",
    "description": "Mẫu thiệp cưới điện ảnh Biển Xanh Lãng Mạn 23 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Biển xanh",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-7",
    "name": "Retro 90s Hoài Niệm 21",
    "category": "hien_dai",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#451a03",
    "accentColor": "#f59e0b",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-7.webp",
    "description": "Mẫu thiệp cưới điện ảnh Retro 90s Vibe 07 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Retro",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-17",
    "name": "Trắng Đen Vĩnh Cửu 22",
    "category": "toi_gian",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#09090b",
    "accentColor": "#71717a",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-17.webp",
    "description": "Mẫu thiệp cưới điện ảnh Trắng Đen Vĩnh Cửu 17 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Monochrome",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-8",
    "name": "Giấc Mơ Chung Đôi 23",
    "category": "hien_dai",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#4c1d95",
    "accentColor": "#c084fc",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-8.webp",
    "description": "Mẫu thiệp cưới điện ảnh Giấc Mơ Tình Yêu 08 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Lãng mạn",
    "isLongThumbnail": true
  },
  {
    "id": "cine-thiep-cuoi-49",
    "name": "Starlight Ngàn Sao 24",
    "category": "hien_dai",
    "source": "cinelove",
    "layoutType": "full_long_card",
    "primaryColor": "#0f172a",
    "accentColor": "#93c5fd",
    "bgTexture": "#0f0f10",
    "cardBg": "#1c1917",
    "envelopeGradient": "from-stone-900 to-black",
    "sealSymbol": "🎬",
    "frameAsset": "/templates/cinelove/cinelove_thiep-cuoi-49.webp",
    "description": "Mẫu thiệp cưới điện ảnh Starlight Wedding 49 thiết kế điện ảnh cao cấp, cuộn dọc sống động và trải nghiệm thảm đỏ sang trọng.",
    "tag": "Ngân hà",
    "isLongThumbnail": true
  },
  {
    "id": "baroque-royal",
    "name": "Baroque Hoàng Gia Quý Tộc",
    "category": "hien_dai",
    "source": "chungdoi",
    "layoutType": "cinelove_movie",
    "primaryColor": "#b45309",
    "accentColor": "#fbbf24",
    "bgTexture": "#faf8f5",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-amber-700 to-yellow-800",
    "sealSymbol": "👑",
    "frameAsset": "/templates/baroque_gold.webp",
    "description": "Thiết kế hoa văn phù điêu Baroque châu Âu cổ điển, dát vàng sang trọng tôn vinh ngày cưới vương giả.",
    "tag": "Hoàng Gia",
    "colorVariants": [
      {
        "id": "baroque-gold",
        "name": "Vàng Kim Quý Tộc",
        "primaryColor": "#b45309",
        "accentColor": "#fbbf24",
        "frameAsset": "/templates/baroque_gold.webp"
      },
      {
        "id": "baroque-v2-darkblue",
        "name": "Xanh Navy Sứ Trắng",
        "primaryColor": "#1d4ed8",
        "accentColor": "#60a5fa",
        "frameAsset": "/templates/baroque_v2_darkblue.webp"
      },
      {
        "id": "baroque-v2-darkgreen",
        "name": "Xanh Lục Bảo",
        "primaryColor": "#047857",
        "accentColor": "#34d399",
        "frameAsset": "/templates/baroque_v2_darkgreen.webp"
      }
    ]
  },
  {
    "id": "song-hy-co-dien",
    "name": "Song Hỷ Cổ Điển Á Đông",
    "category": "truyen_thong",
    "source": "chungdoi",
    "layoutType": "chungdoi_traditional",
    "primaryColor": "#c2182b",
    "accentColor": "#d4af37",
    "bgTexture": "#fff5f5",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-red-600 to-rose-700",
    "sealSymbol": "囍",
    "frameAsset": "/templates/song_hy_red.webp",
    "description": "Nét đẹp truyền thống người Việt với ấn triện Song Hỷ, hoa văn triều đình và lịch âm dương cát nhật.",
    "tag": "Song Hỷ",
    "colorVariants": [
      {
        "id": "song-hy-red",
        "name": "Đỏ Song Hỷ",
        "primaryColor": "#c2182b",
        "accentColor": "#d4af37",
        "frameAsset": "/templates/song_hy_red.webp"
      },
      {
        "id": "classic-red",
        "name": "Đỏ Thắm Trân Châu",
        "primaryColor": "#991b1b",
        "accentColor": "#fbbf24",
        "frameAsset": "/templates/dragon_phoenix_red.webp"
      },
      {
        "id": "gold-crest-red",
        "name": "Vương Triều Dát Vàng",
        "primaryColor": "#881337",
        "accentColor": "#f59e0b",
        "frameAsset": "/templates/baroque_gold.webp"
      }
    ]
  },
  {
    "id": "boho-floral-thao-moc",
    "name": "Boho Floral Thảo Mộc",
    "category": "hoa_la",
    "source": "chungdoi",
    "layoutType": "botanical_garden",
    "primaryColor": "#15803d",
    "accentColor": "#86efac",
    "bgTexture": "#f6fbf7",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-emerald-700 to-green-800",
    "sealSymbol": "🌿",
    "frameAsset": "/templates/boho_floral_green.webp",
    "description": "Họa tiết lá khuynh diệp và thảo mộc phong cách Bohemian phóng khoáng, thích hợp cho đám cưới ngoài trời.",
    "tag": "Boho Garden",
    "colorVariants": [
      {
        "id": "boho-floral-green",
        "name": "Xanh Lá Thảo Mộc",
        "primaryColor": "#15803d",
        "accentColor": "#86efac",
        "frameAsset": "/templates/boho_floral_green.webp"
      },
      {
        "id": "boho-floral-terracotta",
        "name": "Cam Đất Terracotta",
        "primaryColor": "#c2410c",
        "accentColor": "#fdba74",
        "frameAsset": "/templates/boho_floral_brown.webp"
      },
      {
        "id": "boho-floral-navy",
        "name": "Xanh Navy Chiều Tà",
        "primaryColor": "#1e3a8a",
        "accentColor": "#93c5fd",
        "frameAsset": "/templates/chateau_blue.webp"
      }
    ]
  },
  {
    "id": "minimalism-tinh-te",
    "name": "Tối Giản Minimalism Hiện Đại",
    "category": "toi_gian",
    "source": "chungdoi",
    "layoutType": "zenlove_minimal",
    "primaryColor": "#18181b",
    "accentColor": "#71717a",
    "bgTexture": "#fafafa",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-zinc-700 to-zinc-900",
    "sealSymbol": "✨",
    "frameAsset": "/templates/dragon_phoenix_black.webp",
    "description": "Đỉnh cao của sự tinh gọn: Khoảng trắng thanh lịch, typography sắc sảo và lịch tháng đánh dấu trái tim.",
    "tag": "Minimalism",
    "colorVariants": [
      {
        "id": "minimalism-black",
        "name": "Đen Trắng Tinh Tế",
        "primaryColor": "#18181b",
        "accentColor": "#71717a",
        "frameAsset": "/templates/dragon_phoenix_black.webp"
      },
      {
        "id": "minimalism-red",
        "name": "Đỏ Rượu Vang",
        "primaryColor": "#b91c1c",
        "accentColor": "#fca5a5",
        "frameAsset": "/templates/minimalism_red.webp"
      },
      {
        "id": "minimalism-green",
        "name": "Xanh Rêu Mộc",
        "primaryColor": "#065f46",
        "accentColor": "#6ee7b7",
        "frameAsset": "/templates/minimalism_green.webp"
      }
    ]
  },
  {
    "id": "vintage-rose-lang-man",
    "name": "Vintage Rose Hồng Lãng Mạn",
    "category": "hoa_la",
    "source": "chungdoi",
    "layoutType": "botanical_garden",
    "primaryColor": "#be185d",
    "accentColor": "#f9a8d4",
    "bgTexture": "#fff5f7",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-rose-600 to-pink-700",
    "sealSymbol": "🌸",
    "frameAsset": "/templates/cherry_blossom_pink.webp",
    "description": "Vườn hồng cổ nước Pháp với những cánh hoa nở rộ mềm mại, tượng trưng cho tình yêu ngọt ngào, bền chặt.",
    "tag": "Hoa Hồng Cổ",
    "colorVariants": [
      {
        "id": "vintage-rose-pink",
        "name": "Hồng Phấn Ngọt Ngào",
        "primaryColor": "#be185d",
        "accentColor": "#f9a8d4",
        "frameAsset": "/templates/cherry_blossom_pink.webp"
      },
      {
        "id": "vintage-rose-burgundy",
        "name": "Đỏ Bordeaux Say Đắm",
        "primaryColor": "#831843",
        "accentColor": "#fbcfe8",
        "frameAsset": "/templates/silk_ribbon_darkred.webp"
      }
    ]
  },
  {
    "id": "editorial-vogue-lookbook",
    "name": "Tạp Chí Thời Trang Vogue Lookbook",
    "category": "hien_dai",
    "source": "chungdoi",
    "layoutType": "chungdoi_magazine",
    "primaryColor": "#09090b",
    "accentColor": "#d4af37",
    "bgTexture": "#f4f4f5",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-neutral-800 to-black",
    "sealSymbol": "💍",
    "frameAsset": "/templates/minimalism_darkblue.webp",
    "description": "Bố cục trang bìa tạp chí danh tiếng với font chữ Didot, ảnh Lookbook đôi và câu chuyện tình yêu truyền cảm hứng.",
    "tag": "Vogue Fashion",
    "colorVariants": [
      {
        "id": "editorial-classic-black",
        "name": "Bìa Đen Haute Couture",
        "primaryColor": "#09090b",
        "accentColor": "#d4af37",
        "frameAsset": "/templates/minimalism_darkblue.webp"
      },
      {
        "id": "editorial-chic-gold",
        "name": "Ánh Kim Sang Trọng",
        "primaryColor": "#78350f",
        "accentColor": "#fbbf24",
        "frameAsset": "/templates/baroque_gold.webp"
      }
    ]
  },
  {
    "id": "zen-minimal-polaroid",
    "name": "Polaroid Băng Keo Thơ Mộng",
    "category": "toi_gian",
    "source": "zenlove",
    "layoutType": "zenlove_minimal",
    "primaryColor": "#44403c",
    "accentColor": "#a8a29e",
    "bgTexture": "#fafaf9",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-stone-700 to-stone-900",
    "sealSymbol": "🕊️",
    "frameAsset": "/templates/zen_long_03feb3d1-a100-4972-a64a-879c038d14d4.webp",
    "description": "Thiết kế nguyên bản mộc mạc tinh tế: Tấm ảnh dán tape, những dòng thư tình chân thành và giao diện tĩnh lặng.",
    "tag": "Zen Mộc",
    "isLongThumbnail": true
  },
  {
    "id": "zen-botanical-watercolor",
    "name": "Thảo Mộc Màu Nước",
    "category": "hoa_la",
    "source": "zenlove",
    "layoutType": "botanical_garden",
    "primaryColor": "#047857",
    "accentColor": "#6ee7b7",
    "bgTexture": "#f0fdf4",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-emerald-800 to-green-950",
    "sealSymbol": "🍃",
    "frameAsset": "/templates/zen_long_1c312850-dfbb-463a-98a7-729d5b8d7df6.webp",
    "description": "Sự hòa quyện giữa tinh thần tĩnh tại thanh nhã và sắc xanh thảo dược trong trẻo.",
    "tag": "Thảo Dược",
    "isLongThumbnail": true
  },
  {
    "id": "zen-calm-sunset",
    "name": "Hoàng Hôn Tĩnh Lặng",
    "category": "toi_gian",
    "source": "zenlove",
    "layoutType": "zenlove_minimal",
    "primaryColor": "#9a3412",
    "accentColor": "#fdba74",
    "bgTexture": "#fff7ed",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-amber-800 to-orange-950",
    "sealSymbol": "🌅",
    "frameAsset": "/templates/zen_long_1f422dc5-7795-48c4-8e1a-48cc8421dbc3.webp",
    "description": "Màu ấm hoàng hôn mang lại cảm giác bình yên và ấm áp cho ngày chung đôi.",
    "tag": "Hoàng Hôn",
    "isLongThumbnail": true
  },
{
    "id": "motdoi-duyen-dang-01",
    "name": "Duyên Dáng Tinh Khôi 01",
    "category": "toi_gian",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#991b1b",
    "accentColor": "#d4af37",
    "bgTexture": "#fafaf9",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-red-900 to-rose-950",
    "sealSymbol": "💌",
    "frameAsset": "/templates/motdoi/graceful-01.png",
    "description": "Nền trắng tinh tế, tông đỏ son trầm sang trọng. Mở phong bì lãng mạn để khám phá thiệp — đơn giản, cổ điển và đầy cảm xúc.",
    "tag": "Tối giản",
    "isLongThumbnail": true
},
{
    "id": "motdoi-duyen-dang-04",
    "name": "Album Kỷ Niệm Vĩnh Cửu 02",
    "category": "hien_dai",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#78350f",
    "accentColor": "#fbbf24",
    "bgTexture": "#fdfbf7",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-amber-800 to-amber-950",
    "sealSymbol": "📖",
    "frameAsset": "/templates/motdoi/graceful-04.jpg",
    "description": "Duyên dáng 04 mang tinh thần của một cuốn album cưới được lưu giữ qua năm tháng, kết hợp nền giấy kem, sắc vàng champagne và những khung ảnh nghiêng tự nhiên.",
    "tag": "Sang trọng",
    "isLongThumbnail": true
},
{
    "id": "motdoi-truyen-thong-01",
    "name": "Hồng Hỷ Á Đông 03",
    "category": "truyen_thong",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#b91c1c",
    "accentColor": "#f59e0b",
    "bgTexture": "#fef2f2",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-red-800 to-rose-900",
    "sealSymbol": "囍",
    "frameAsset": "/templates/motdoi/traditional-01.png",
    "description": "Sang trọng, cổ điển — nền kem thanh lịch, sắc đỏ thẫm và chữ Hỷ truyền thống, mang đậm nét văn hóa Á Đông.",
    "tag": "Truyền thống",
    "isLongThumbnail": true
},
{
    "id": "motdoi-hoa-dau-biec",
    "name": "Hoa Đậu Biếc Thanh Lịch 04",
    "category": "hoa_la",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#1e40af",
    "accentColor": "#93c5fd",
    "bgTexture": "#eff6ff",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-blue-800 to-indigo-950",
    "sealSymbol": "🌸",
    "frameAsset": "/templates/motdoi/hoa-dau-biec.jpg",
    "description": "Hoa Đậu Biếc mang sắc xanh thanh lịch, họa tiết hoa mềm mại và vẻ lãng mạn đầy tinh tế.",
    "tag": "Hoa lá",
    "isLongThumbnail": true
},
{
    "id": "motdoi-duyen-dang-02",
    "name": "Sáp Niêm Rượu Vang 05",
    "category": "hien_dai",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#831843",
    "accentColor": "#f472b6",
    "bgTexture": "#fdf2f8",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-rose-900 to-pink-950",
    "sealSymbol": "💍",
    "frameAsset": "/templates/motdoi/graceful-02.png",
    "description": "Mẫu thiệp cổ điển với phong bì niêm phong sáp, tông màu rượu vang sâu, tinh tế và sang trọng.",
    "tag": "Sang trọng",
    "isLongThumbnail": true
},
{
    "id": "motdoi-duyen-dang-pastel",
    "name": "Cánh Hồng Pastel 06",
    "category": "hoa_la",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#db2777",
    "accentColor": "#fbcfe8",
    "bgTexture": "#fff1f2",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-pink-600 to-rose-700",
    "sealSymbol": "🎀",
    "frameAsset": "/templates/motdoi/graceful-pastel.jpg",
    "description": "Mẫu thiệp cưới hồng pastel thanh lịch với hiệu ứng mở cánh, chất liệu giấy mềm, phong bì ảnh và album kỷ niệm lãng mạn.",
    "tag": "Pastel",
    "isLongThumbnail": true
},
{
    "id": "motdoi-thien-nhien-01",
    "name": "Khu Vườn Tình Yêu 07",
    "category": "hoa_la",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#15803d",
    "accentColor": "#86efac",
    "bgTexture": "#f0fdf4",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-green-800 to-emerald-950",
    "sealSymbol": "🌿",
    "frameAsset": "/templates/motdoi/nature-01.png",
    "description": "Hơi thở thiên nhiên thuần khiết — xanh mát, ấm áp và lãng mạn như những khoảnh khắc tình yêu được giữ mãi trong tim.",
    "tag": "Thiên nhiên",
    "isLongThumbnail": true
},
{
    "id": "motdoi-thanh-manh",
    "name": "Thanh Mảnh Tối Giản 08",
    "category": "toi_gian",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#374151",
    "accentColor": "#9ca3af",
    "bgTexture": "#f9fafb",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-gray-700 to-stone-900",
    "sealSymbol": "✒️",
    "frameAsset": "/templates/motdoi/thanh-manh.jpg",
    "description": "Mẫu thiệp cưới thanh lịch với nền trắng kem, điểm nhấn đỏ rượu, chữ viết tay mềm mại và bố cục ảnh thoáng nhẹ.",
    "tag": "Tối giản",
    "isLongThumbnail": true
},
{
    "id": "motdoi-ho-chieu",
    "name": "Hộ Chiếu Tình Yêu Hạnh Phúc 09",
    "category": "hien_dai",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#1e3a8a",
    "accentColor": "#f59e0b",
    "bgTexture": "#eff6ff",
    "cardBg": "#1e3a8a",
    "envelopeGradient": "from-blue-900 to-slate-950",
    "sealSymbol": "✈️",
    "frameAsset": "/templates/motdoi/passport.png",
    "description": "Một tấm thiệp như cuốn hộ chiếu tình yêu, mở ra chuyến bay của hai trái tim đến miền hạnh phúc, nơi lời hẹn ước hóa thành hành trình mãi mãi.",
    "tag": "Hộ Chiếu",
    "isLongThumbnail": true
},
{
    "id": "motdoi-hoa-be",
    "name": "Hoa Cỏ Trầm Ấm 10",
    "category": "hoa_la",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#78350f",
    "accentColor": "#fde68a",
    "bgTexture": "#fffbeb",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-stone-700 to-amber-950",
    "sealSymbol": "🌼",
    "frameAsset": "/templates/motdoi/hoa-be.jpg",
    "description": "Mẫu thiệp cưới màu be thanh lịch, giữ nguyên bố cục giàu chi tiết của Hoa Đậu Biếc với hoa màu ivory, sắc champagne, nâu mocha và nền giấy ấm.",
    "tag": "Hoa Be",
    "isLongThumbnail": true
},
{
    "id": "motdoi-duyen-dang-03",
    "name": "Sen Hồng Duyên Dáng 11",
    "category": "truyen_thong",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#991b1b",
    "accentColor": "#f59e0b",
    "bgTexture": "#fef2f2",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-red-900 to-rose-950",
    "sealSymbol": "🪷",
    "frameAsset": "/templates/motdoi/graceful-03.png",
    "description": "Sắc đỏ trầm, nền kem thanh nhã, hoa sen duyên dáng, gợi không khí cưới truyền thống.",
    "tag": "Hoa Sen",
    "isLongThumbnail": true
},
{
    "id": "motdoi-chibi",
    "name": "Chibi Dâu Rể Đáng Yêu 12",
    "category": "hien_dai",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#dc2626",
    "accentColor": "#fde047",
    "bgTexture": "#fef2f2",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-red-600 to-rose-700",
    "sealSymbol": "🥰",
    "frameAsset": "/templates/motdoi/chibi.png",
    "description": "Thiệp cưới chibi đáng yêu, khắc họa cô dâu chú rể sinh động, mang nét vui tươi và dấu ấn riêng.",
    "tag": "Chibi",
    "isLongThumbnail": true
},
{
    "id": "motdoi-lang-man-gold",
    "name": "Champagne Gold Hoàng Gia 13",
    "category": "hien_dai",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#b45309",
    "accentColor": "#fcd34d",
    "bgTexture": "#fffbeb",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-amber-700 to-yellow-900",
    "sealSymbol": "✨",
    "frameAsset": "/templates/motdoi/romantic-gold.png",
    "description": "Vàng champagne lấp lánh trên nền kem sáng sang trọng — ấm áp, tinh tế, dành cho lễ cưới muốn toát lên vẻ cao quý và đặc biệt.",
    "tag": "Gold",
    "isLongThumbnail": true
},
{
    "id": "motdoi-suong-mai",
    "name": "Sương Mai Ban Sớm 14",
    "category": "toi_gian",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#0f766e",
    "accentColor": "#99f6e4",
    "bgTexture": "#f0fdfa",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-teal-800 to-cyan-950",
    "sealSymbol": "💧",
    "frameAsset": "/templates/motdoi/suong-mai.png",
    "description": "Sương Mai mang vẻ tinh khôi của buổi sớm, dịu dàng như lời hẹn đầu ngày, nơi tình yêu nở trong ánh sáng mỏng, yên bình và đầy hy vọng.",
    "tag": "Sương Mai",
    "isLongThumbnail": true
},
{
    "id": "motdoi-lang-man-hoa-hong",
    "name": "Hoa Hồng Mùa Xuân 15",
    "category": "hoa_la",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#e11d48",
    "accentColor": "#fecdd3",
    "bgTexture": "#fff1f2",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-rose-600 to-pink-800",
    "sealSymbol": "🌹",
    "frameAsset": "/templates/motdoi/romantic-rose.png",
    "description": "Tông hồng đào ngọt ngào, nền giấy kem sáng với họa tiết cành lá — lãng mạn, nữ tính, phù hợp cho đám cưới phong cách mùa xuân.",
    "tag": "Hoa Hồng",
    "isLongThumbnail": true
},
{
    "id": "motdoi-song-hy",
    "name": "Trăm Năm Hạnh Phúc Song Hỷ 16",
    "category": "truyen_thong",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#b91c1c",
    "accentColor": "#fbbf24",
    "bgTexture": "#fef2f2",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-red-800 to-red-950",
    "sealSymbol": "囍",
    "frameAsset": "/templates/motdoi/song-hy.png",
    "description": "Song Hỷ mang nét đẹp truyền thống Á Đông, sắc đỏ may mắn, họa tiết tinh tế, gửi gắm lời chúc trăm năm hạnh phúc.",
    "tag": "Song Hỷ",
    "isLongThumbnail": true
},
{
    "id": "motdoi-xanh-thanh-lich",
    "name": "Xanh Ngọc Bảo Cổ Điển 17",
    "category": "hoa_la",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#064e3b",
    "accentColor": "#a7f3d0",
    "bgTexture": "#ecfdf5",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-emerald-900 to-teal-950",
    "sealSymbol": "🍃",
    "frameAsset": "/templates/motdoi/elegant-green.png",
    "description": "Xanh rừng thẫm sâu với họa tiết hoa trắng nổi bật — trang nhã, cổ điển, ấn tượng cho đám cưới muốn vẻ đẹp trưởng thành và bí ẩn.",
    "tag": "Xanh Rừng",
    "isLongThumbnail": true
},
{
    "id": "motdoi-do-thanh-lich",
    "name": "Đỏ Bordeaux Quý Phái 18",
    "category": "truyen_thong",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#881337",
    "accentColor": "#fca5a5",
    "bgTexture": "#fff1f2",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-rose-900 to-stone-950",
    "sealSymbol": "👑",
    "frameAsset": "/templates/motdoi/elegant-red.png",
    "description": "Đỏ thẫm đam mê trên nền tối sang trọng, họa tiết hoa tinh xảo — mạnh mẽ, nồng nàn, tạo ấn tượng không thể quên cho ngày trọng đại.",
    "tag": "Đỏ Thẫm",
    "isLongThumbnail": true
},
{
    "id": "motdoi-tap-chi",
    "name": "Tạp Chí Cưới Châu Âu 19",
    "category": "hien_dai",
    "source": "motdoi",
    "layoutType": "full_long_card",
    "primaryColor": "#292524",
    "accentColor": "#d97706",
    "bgTexture": "#fafaf9",
    "cardBg": "#ffffff",
    "envelopeGradient": "from-stone-800 to-zinc-950",
    "sealSymbol": "🗞️",
    "frameAsset": "/templates/motdoi/edition-ivory.png",
    "description": "Mẫu thiệp mang phong cách tạp chí thanh lịch, giấy ngà ấm, mực sâu và điểm nhấn đất nung tinh tế.",
    "tag": "Tạp Chí",
    "isLongThumbnail": true
}
];

export interface BankConfig {
  code: string;
  name: string;
  bin: string;
}

export const VIETNAMESE_BANKS: BankConfig[] = [
  { code: 'MB', name: 'MBBank (Quân Đội)', bin: '970422' },
  { code: 'VCB', name: 'Vietcombank', bin: '970436' },
  { code: 'TCB', name: 'Techcombank', bin: '970407' },
  { code: 'ACB', name: 'ACB Á Châu', bin: '970416' },
  { code: 'VPB', name: 'VPBank', bin: '970432' },
  { code: 'BIDV', name: 'BIDV', bin: '970418' },
  { code: 'VIB', name: 'VIB Quốc Tế', bin: '970441' },
  { code: 'TPB', name: 'TPBank', bin: '970423' },
  { code: 'STB', name: 'Sacombank', bin: '970403' },
  { code: 'HDB', name: 'HDBank', bin: '970437' },
  { code: 'OCB', name: 'OCB Phương Đông', bin: '970448' },
  { code: 'CTG', name: 'VietinBank', bin: '970415' }
];

export const DEFAULT_WEDDING_DATA = {
  id: 'mau-thiep-demo',
  slug: 'thanh-tung-lan-anh',
  templateId: 'cine-thiep-cuoi-61',
  themeName: 'Điện Ảnh Hiện Đại 01',
  primaryColor: '#1c1917',
  fontFamily: 'Pattaya',
  musicTrackUrl: '/audio/anh-nang-cua-anh.mp3',
  musicTitle: 'Ánh Nắng Của Anh - Đức Phúc (Bản Có Lời)',
  fallingEffect: 'petals' as const,

  groom: {
    fullName: 'Trần Thanh Tùng',
    shortName: 'Thanh Tùng',
    birthOrder: 'Trưởng Nam',
    fatherName: 'Trần Quang Vinh',
    motherName: 'Nguyễn Thị Tuyết',
    address: '124 Hoàng Hoa Thám, Ba Đình, Hà Nội',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80',
    bank: {
      bankCode: 'MB',
      bankName: 'MBBank',
      accountNumber: '0988889999',
      accountName: 'TRAN THANH TUNG',
      qrUrl: 'https://img.vietqr.io/image/MB-0988889999-compact2.png?amount=0&addInfo=Mung+cuoi+Tung+Anh'
    }
  },

  bride: {
    fullName: 'Lê Lan Anh',
    shortName: 'Lan Anh',
    birthOrder: 'Ái Nữ',
    fatherName: 'Lê Văn Hoàng',
    motherName: 'Phạm Thu Hương',
    address: '56 Nguyễn Đình Chiểu, Quận 3, TP. Hồ Chí Minh',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&auto=format&fit=crop&q=80',
    bank: {
      bankCode: 'VCB',
      bankName: 'Vietcombank',
      accountNumber: '9988776655',
      accountName: 'LE LAN ANH',
      qrUrl: 'https://img.vietqr.io/image/VCB-9988776655-compact2.png?amount=0&addInfo=Mung+cuoi+Tung+Anh'
    }
  },

  loveStory: {
    title: 'Hành Trình Tình Yêu',
    content: 'Từ ánh nhìn đầu tiên dưới cơn mưa rào Hà Nội đến ngày ta nguyện chung đôi trên con đường hạnh phúc.',
    quotes: '“Hôn nhân không phải là tìm một người hoàn hảo, mà là cùng nhau vun đắp một tình yêu vẹn nguyên.”'
  },

  ceremonies: [
    {
      id: 'c1',
      type: 'vu_quy' as const,
      title: 'LỄ VU QUY (NHÀ GÁI)',
      dateSolar: '2026-10-24',
      dateLunar: '15 Tháng 9 Năm Bính Ngọ',
      time: '09:00',
      venueName: 'Tư gia Nhà Gái',
      address: '56 Nguyễn Đình Chiểu, Phường Võ Thị Sáu, Quận 3, TP.HCM',
      mapUrl: 'https://maps.google.com/?q=District+3+Ho+Chi+Minh',
      note: 'Gia đình Nhà Gái hân hạnh đón tiếp'
    },
    {
      id: 'c2',
      type: 'thanh_hon' as const,
      title: 'LỄ THÀNH HÔN (NHÀ TRAI)',
      dateSolar: '2026-10-25',
      dateLunar: '16 Tháng 9 Năm Bính Ngọ',
      time: '11:00',
      venueName: 'Tư gia Nhà Trai',
      address: '124 Hoàng Hoa Thám, Ba Đình, Hà Nội',
      mapUrl: 'https://maps.google.com/?q=Ba+Dinh+Ha+Noi',
      note: 'Gia đình Nhà Trai hân hạnh đón tiếp'
    },
    {
      id: 'c3',
      type: 'tiec_cuoi' as const,
      title: 'TIỆC CƯỚI CHUNG VUI',
      dateSolar: '2026-10-25',
      dateLunar: '16 Tháng 9 Năm Bính Ngọ',
      time: '18:00',
      venueName: 'Trung Tâm Tiệc Cưới Grand Palace',
      address: '142/18 Cộng Hòa, Phường 4, Quận Tân Bình, TP.HCM',
      mapUrl: 'https://maps.google.com/?q=Grand+Palace+Cong+Hoa',
      note: 'Rất hân hạnh được đón tiếp Quý Khách'
    }
  ],

  heroPhoto: '',
  galleryImages: [
    'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1606800052052-a08af7148866?w=800&auto=format&fit=crop&q=80'
  ],

  enableMusic: true,
  enableVietQR: true,
  enableGuestbook: true,
  enableRSVP: true,
  thankYouMessage: 'Sự hiện diện và lời chúc phúc của Quý Khách là niềm vinh hạnh to lớn cho gia đình chúng tôi!',

  dressCode: {
    enabled: true,
    title: 'Dress Code & Gợi Ý Trang Phục',
    description: 'Để buổi tiệc thêm phần trang trọng và những bức hình kỷ niệm thật hài hòa, kính mong Quý Khách ưu tiên trang phục theo các gam màu gợi ý dưới đây:',
    colors: [
      { name: 'Trắng Sữa', hex: '#FAF9F6' },
      { name: 'Be / Pastel', hex: '#EAD7C5' },
      { name: 'Nâu Đất', hex: '#C27D56' },
      { name: 'Xanh Sage', hex: '#8FA392' },
      { name: 'Vàng Cát', hex: '#D1AC00' }
    ]
  }
};
