export interface ZenLoveTemplate {
  id: string;
  name: string;
  slug: string;
  category: 'thiep-cuoi' | 'thiep-tot-nghiep' | 'thiep-sinh-nhat' | 'khac';
  templateType: 'free' | 'premium' | 'basic';
  tag?: string;
  description: string;
  longThumbnailUrl: string;
  thumbnailUrl: string;
  likeCount: number;
  viewCount: number;
}

export function findZenLoveTemplate(slugOrId?: string | null): ZenLoveTemplate | undefined {
  if (!slugOrId) return undefined;
  return ZENLOVE_TEMPLATES.find((t) => t.slug === slugOrId || t.id === slugOrId);
}

export const ZENLOVE_TEMPLATES: ZenLoveTemplate[] = [
  {
    "id": "a9195353-7ba5-4a2b-9611-5868025d3f02",
    "name": "Sen Ngày Hỷ",
    "slug": "sen-ngay-hy",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online Sen Ngày Hỷ với họa tiết hoa sen thanh nhã, mang vẻ đẹp truyền thống và tinh tế, phù hợp cho những cặp đôi yêu thích phong cách Á Đông.",
    "longThumbnailUrl": "/templates/lien_hoa_pink.webp",
    "thumbnailUrl": "/templates/lien_hoa_pink.webp",
    "likeCount": 0,
    "viewCount": 33
  },
  {
    "id": "4ec76647-a5ef-4f58-8160-d20febb9e84a",
    "name": "Hẹn Ước",
    "slug": "hen-uoc",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online thanh lịch, nhẹ nhàng với thiết kế tinh tế, phù hợp cho những cặp đôi yêu thích phong cách tối giản và lãng mạn.",
    "longThumbnailUrl": "/templates/minimalism_brown.webp",
    "thumbnailUrl": "/templates/minimalism_brown.webp",
    "likeCount": 5,
    "viewCount": 84
  },
  {
    "id": "8c5055d8-30db-4b38-8831-e11063e3d352",
    "name": "Hồng Phong",
    "slug": "hong-phong",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Hot",
    "description": "Hồng Phong – Mẫu thiệp cưới online màu đỏ sang trọng, nổi bật với thiết kế phong bì tinh tế ở phần mở đầu. Phù hợp cho các cặp đôi yêu thích vẻ đẹp truyền thống, ấm áp và trang trọng.",
    "longThumbnailUrl": "/templates/nhat_binh_red.webp",
    "thumbnailUrl": "/templates/nhat_binh_red.webp",
    "likeCount": 64,
    "viewCount": 1000
  },
  {
    "id": "84db03a1-1d4a-4274-a0bc-a8419d90e4be",
    "name": "Rước Đèn Ông Sao",
    "slug": "ruoc-den-ong-sao",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Rước Đèn Ông Sao – Mẫu thiệp Trung Thu online mang không khí vui tươi, rực rỡ và đậm nét tuổi thơ. Thiết kế phù hợp gửi lời chúc Trung Thu đến gia đình, bạn bè, khách hàng và người thân trên ZenLove.",
    "longThumbnailUrl": "/templates/chibi_red.webp",
    "thumbnailUrl": "/templates/chibi_red.webp",
    "likeCount": 10,
    "viewCount": 59
  },
  {
    "id": "328c2d89-01d9-486f-b245-10362d2fbaa0",
    "name": "Đêm hội Trăng tròn",
    "slug": "trung-thu-01",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Trung Thu 01 – Mẫu thiệp Trung Thu online mang phong cách ấm áp, tinh tế, kết hợp sắc màu truyền thống và thiết kế hiện đại. Phù hợp g���i lời chúc Trung Thu ý nghĩa đến gia đình, bạn bè và người thân trên ZenLove.",
    "longThumbnailUrl": "/templates/spring_garden_red.webp",
    "thumbnailUrl": "/templates/spring_garden_red.webp",
    "likeCount": 10,
    "viewCount": 72
  },
  {
    "id": "1f422dc5-7795-48c4-8e1a-48cc8421dbc3",
    "name": "Mộc Ấm",
    "slug": "moc-am",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Hot",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/boho_floral_brown.webp",
    "thumbnailUrl": "/templates/boho_floral_brown.webp",
    "likeCount": 11,
    "viewCount": 102
  },
  {
    "id": "24d88c9e-159b-4888-9c77-c3ed775035b6",
    "name": "Đồng Xanh",
    "slug": "dong-xanh",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Hot",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/spring_garden_green.webp",
    "thumbnailUrl": "/templates/spring_garden_green.webp",
    "likeCount": 18,
    "viewCount": 208
  },
  {
    "id": "de48d917-df7d-4ab9-a553-be6e8fd84c04",
    "name": "Nét Thương",
    "slug": "net-thuong",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/silk_ribbon_pink.webp",
    "thumbnailUrl": "/templates/silk_ribbon_pink.webp",
    "likeCount": 10,
    "viewCount": 100
  },
  {
    "id": "3d7badec-67c8-4eb3-90a4-bf96d2948ec8",
    "name": "Lời Hẹn Kem",
    "slug": "loi-hen-kem",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Hot",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/silk_flora_brown.webp",
    "thumbnailUrl": "/templates/silk_flora_brown.webp",
    "likeCount": 17,
    "viewCount": 123
  },
  {
    "id": "3410d8c2-6141-4c75-8848-445353a884b5",
    "name": "Sắc Cười Be",
    "slug": "sac-cuoi-be",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/minimalism_brown.webp",
    "thumbnailUrl": "/templates/minimalism_brown.webp",
    "likeCount": 9,
    "viewCount": 100
  },
  {
    "id": "3b6728a2-bb39-4331-82f6-410eca19f9db",
    "name": "Lời Hẹn Cổ Điển",
    "slug": "loi-hen-co-dien",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/baroque_gold.webp",
    "thumbnailUrl": "/templates/baroque_gold.webp",
    "likeCount": 13,
    "viewCount": 69
  },
  {
    "id": "917772d9-d56c-43ca-b671-12f7023f01ce",
    "name": "Nắng Trắng Ngời",
    "slug": "nang-trang-ngoi",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Hot",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/jasmine_white.webp",
    "thumbnailUrl": "/templates/jasmine_white.webp",
    "likeCount": 16,
    "viewCount": 108
  },
  {
    "id": "f97f767a-b8c2-438d-80e9-89651095e93e",
    "name": "Trắng Tinh Khôi",
    "slug": "trang-tinh-khoi",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/spring_garden_blue.webp",
    "thumbnailUrl": "/templates/spring_garden_blue.webp",
    "likeCount": 17,
    "viewCount": 91
  },
  {
    "id": "453f372e-5d22-474e-b947-0a833ba1bb66",
    "name": "Hồng Yêu Thương",
    "slug": "hong-yeu-thuong",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/boho_floral_pink.webp",
    "thumbnailUrl": "/templates/boho_floral_pink.webp",
    "likeCount": 5,
    "viewCount": 80
  },
  {
    "id": "c0031611-6847-4945-b7f5-f98ddaf5f1ee",
    "name": "Sắc Đêm Hẹn",
    "slug": "sac-dem-hen",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/baroque_v2_darkblue.webp",
    "thumbnailUrl": "/templates/baroque_v2_darkblue.webp",
    "likeCount": 3,
    "viewCount": 50
  },
  {
    "id": "c026f536-0230-4d5e-80af-7533f26eed61",
    "name": "Lá Mộng Ô Liu",
    "slug": "la-mong-o-liu",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/elegant_leaf_green.webp",
    "thumbnailUrl": "/templates/elegant_leaf_green.webp",
    "likeCount": 4,
    "viewCount": 99
  },
  {
    "id": "8b92bbcd-83d7-46d9-b522-8c61042b0342",
    "name": "Khung Mây Trắng",
    "slug": "khung-may-trang",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/glass_garden_blue.webp",
    "thumbnailUrl": "/templates/glass_garden_blue.webp",
    "likeCount": 10,
    "viewCount": 91
  },
  {
    "id": "43498986-ba34-4bcf-857a-0a4caa8d7dcb",
    "name": "Nắng Lưu Yêu",
    "slug": "nang-luu-yeu",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Hot",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/hoa_kho_orange.webp",
    "thumbnailUrl": "/templates/hoa_kho_orange.webp",
    "likeCount": 12,
    "viewCount": 106
  },
  {
    "id": "82f29721-5471-4784-b3f8-bee9afa7c790",
    "name": "Xanh Như Lời Hẹn",
    "slug": "xanh-nhu-loi-hen",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/glass_garden_green.webp",
    "thumbnailUrl": "/templates/glass_garden_green.webp",
    "likeCount": 12,
    "viewCount": 97
  },
  {
    "id": "b546553f-34a8-4313-a259-a79933725b70",
    "name": "Nét Chữ Tình Nhân",
    "slug": "net-chu-tinh-nhan",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/minimalism_darkblue.webp",
    "thumbnailUrl": "/templates/minimalism_darkblue.webp",
    "likeCount": 3,
    "viewCount": 72
  },
  {
    "id": "b36690e6-ca43-45a7-83e5-4f5aa66aedd1",
    "name": "Sắc Be Thanh Lịch",
    "slug": "sac-be-thanh-lich",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Hot",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/minimalism_brown.webp",
    "thumbnailUrl": "/templates/minimalism_brown.webp",
    "likeCount": 10,
    "viewCount": 121
  },
  {
    "id": "9ab4a8a1-5093-4172-8e5c-ebd83333cac6",
    "name": "Yêu Như Ban Đầu",
    "slug": "yeu-nhu-ban-dau",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/cherry_blossom_pink.webp",
    "thumbnailUrl": "/templates/cherry_blossom_pink.webp",
    "likeCount": 13,
    "viewCount": 98
  },
  {
    "id": "5ba8fc8b-04a4-446f-a99d-62b58deab425",
    "name": "Cánh Đồng Yêu Thương",
    "slug": "canh-dong-yeu-thuong",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/sunflower.webp",
    "thumbnailUrl": "/templates/sunflower.webp",
    "likeCount": 12,
    "viewCount": 71
  },
  {
    "id": "1557dc9e-59be-40be-a2d1-858eb4152abc",
    "name": "Hồng Hạnh Phúc",
    "slug": "hong-hanh-phuc",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/silk_ribbon_pink.webp",
    "thumbnailUrl": "/templates/silk_ribbon_pink.webp",
    "likeCount": 11,
    "viewCount": 65
  },
  {
    "id": "ddcb6880-b730-40b7-b95b-4104c1d8c971",
    "name": "Sắc Xanh Dịu Êm",
    "slug": "sac-xanh-diu-em",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/chateau_blue.webp",
    "thumbnailUrl": "/templates/chateau_blue.webp",
    "likeCount": 10,
    "viewCount": 52
  },
  {
    "id": "0ff5ab5f-dde3-4798-85ab-59dbd629c7aa",
    "name": "Cổ Điển Tinh Khôi",
    "slug": "co-dien-tinh-khoi",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/porcelain_blue.webp",
    "thumbnailUrl": "/templates/porcelain_blue.webp",
    "likeCount": 9,
    "viewCount": 64
  },
  {
    "id": "5592f05c-7056-4ce7-9003-92e2454dadde",
    "name": "Nét Đậm Yêu Thương",
    "slug": "net-dam-yeu-thuong",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/porcelain_red.webp",
    "thumbnailUrl": "/templates/porcelain_red.webp",
    "likeCount": 11,
    "viewCount": 100
  },
  {
    "id": "0ddfdf72-cdb4-4a57-8dde-43a09def7fdf",
    "name": "Vòm Mây Hồng",
    "slug": "vom-may-hong",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/porcelain_v2_pink.webp",
    "thumbnailUrl": "/templates/porcelain_v2_pink.webp",
    "likeCount": 9,
    "viewCount": 49
  },
  {
    "id": "eea9e7bb-3c7f-414e-9525-74d4f4a9d103",
    "name": "Nắng Xanh Thủy Tinh",
    "slug": "nang-xanh-thuy-tinh",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/porcelain_v2_green.webp",
    "thumbnailUrl": "/templates/porcelain_v2_green.webp",
    "likeCount": 11,
    "viewCount": 78
  },
  {
    "id": "c554c6f7-1105-4ce4-8b37-8e24921ec837",
    "name": "Chiều Nâu Điện Ảnh",
    "slug": "chieu-nau-dien-anh",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-61.jpg",
    "thumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-61.jpg",
    "likeCount": 11,
    "viewCount": 88
  },
  {
    "id": "fb4cd6a2-61be-451c-a2e2-8aeb9a8c415d",
    "name": "Hẹn Ước Tân Thời",
    "slug": "hen-uoc-tan-thoi",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-39.jpeg",
    "thumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-39.jpeg",
    "likeCount": 9,
    "viewCount": 43
  },
  {
    "id": "f9f1a356-96a8-473c-b83e-32ef2b525a3a",
    "name": "Dấu Yêu Ngày Cũ",
    "slug": "dau-yeu-ngay-cu",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-40.jpeg",
    "thumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-40.jpeg",
    "likeCount": 9,
    "viewCount": 56
  },
  {
    "id": "cbb0cfb6-a823-4966-abed-9fb9aee38610",
    "name": "Khung Đêm Dịu Êm",
    "slug": "khung-dem-diu-em",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-16.jpg",
    "thumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-16.jpg",
    "likeCount": 9,
    "viewCount": 79
  },
  {
    "id": "03feb3d1-a100-4972-a64a-879c038d14d4",
    "name": "Khởi Đầu Yêu",
    "slug": "khoi-dau-yeu",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Hot",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-1.webp",
    "thumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-1.webp",
    "likeCount": 11,
    "viewCount": 106
  },
  {
    "id": "8cde8307-2139-4447-951b-45f552019b0d",
    "name": "Một Sắc Thương",
    "slug": "mot-sac-thuong",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-2.webp",
    "thumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-2.webp",
    "likeCount": 11,
    "viewCount": 47
  },
  {
    "id": "dcdb503f-a949-4ac8-83c9-0f73c3f3fec3",
    "name": "Nét Duyên Thanh",
    "slug": "net-duyen-thanh",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-5.webp",
    "thumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-5.webp",
    "likeCount": 12,
    "viewCount": 58
  },
  {
    "id": "6df56fe1-85c0-4b6e-9559-bdb416304d00",
    "name": "Nét Hoàng Hôn",
    "slug": "net-hoang-hon",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-38.png",
    "thumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-38.png",
    "likeCount": 10,
    "viewCount": 61
  },
  {
    "id": "c7187f03-8cf8-430a-addd-dbbaa70f53df",
    "name": "Sắc Kem Mềm",
    "slug": "sac-kem-mem",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-44.jpg",
    "thumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-44.jpg",
    "likeCount": 11,
    "viewCount": 37
  },
  {
    "id": "9ba03f1b-5918-4164-b9e6-85a9db05224b",
    "name": "Mộng Thư",
    "slug": "mong-thu",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-46.jpg",
    "thumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-46.jpg",
    "likeCount": 10,
    "viewCount": 42
  },
  {
    "id": "cfc4c65e-7983-499f-949e-67a72f0e3cc3",
    "name": "Sắc Yêu",
    "slug": "sac-yeu",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-47.jpeg",
    "thumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-47.jpeg",
    "likeCount": 9,
    "viewCount": 36
  },
  {
    "id": "327261ec-0cc6-42ca-a60d-932980dbdd82",
    "name": "Sắc Hồng",
    "slug": "sac-hong",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-23.jpeg",
    "thumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-23.jpeg",
    "likeCount": 10,
    "viewCount": 51
  },
  {
    "id": "95ab57bc-41aa-4ff3-b61d-d99a62f1fb7b",
    "name": "Thiệp Cưới 132 Premium",
    "slug": "thiep-cuoi-132-premium",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Hot",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-114.png",
    "thumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-114.png",
    "likeCount": 23,
    "viewCount": 285
  },
  {
    "id": "a3f77c89-9ccb-416c-a84a-13ef8ddd9657",
    "name": "Song Phụng - Hỷ Thanh",
    "slug": "song-phung-hy-thanh",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Mới",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/double_phoenix_green.webp",
    "thumbnailUrl": "/templates/double_phoenix_green.webp",
    "likeCount": 11,
    "viewCount": 93
  },
  {
    "id": "ce1dea7d-0138-4364-8a33-7ab8fd95c5fd",
    "name": "Thiệp Cưới 131 Basic",
    "slug": "thiep-cuoi-131-basic",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Hot",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-42.jpg",
    "thumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-42.jpg",
    "likeCount": 16,
    "viewCount": 215
  },
  {
    "id": "40bc54e4-1581-4e01-ad97-6162ac1a5743",
    "name": "Thiệp Cưới 130 Pre",
    "slug": "thiep-cuoi-130-pre",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Hot",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-17.jpeg",
    "thumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-17.jpeg",
    "likeCount": 19,
    "viewCount": 264
  },
  {
    "id": "97041aaf-a789-4dea-a1a7-eefea0af5879",
    "name": "Thiệp Cưới 129 Pre",
    "slug": "thiep-cuoi-129-pre",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Hot",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-36.jpeg",
    "thumbnailUrl": "/templates/clean/clean_cine_thiep-cuoi-36.jpeg",
    "likeCount": 24,
    "viewCount": 505
  },
  {
    "id": "448f3260-a1a5-45f2-8ade-86a2065a1888",
    "name": "Song Hỷ - Hồng Liên",
    "slug": "song-hy-hong-lien",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Hot",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/song_hy_red.webp",
    "thumbnailUrl": "/templates/song_hy_red.webp",
    "likeCount": 25,
    "viewCount": 330
  },
  {
    "id": "23da9a74-eb25-47f0-b726-b50fe6f1b235",
    "name": "Song Hỷ - Thanh Ngọc",
    "slug": "song-hy-thanh-ngoc",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Hot",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/song_hy_green.webp",
    "thumbnailUrl": "/templates/song_hy_green.webp",
    "likeCount": 22,
    "viewCount": 321
  },
  {
    "id": "c3a4b54b-dbe8-4386-87ec-e30dd918e8fe",
    "name": "Bích Ngọc",
    "slug": "bich-ngoc",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Hot",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/chateau_green.webp",
    "thumbnailUrl": "/templates/chateau_green.webp",
    "likeCount": 8,
    "viewCount": 102
  },
  {
    "id": "1c312850-dfbb-463a-98a7-729d5b8d7df6",
    "name": "Chu Sa",
    "slug": "chu-sa",
    "category": "thiep-cuoi",
    "templateType": "free",
    "tag": "Hot",
    "description": "Mẫu thiệp cưới online đẹp tinh tế cho cặp đôi gửi lời mời qua link Zalo, Facebook.",
    "longThumbnailUrl": "/templates/co_ba_red.webp",
    "thumbnailUrl": "/templates/co_ba_red.webp",
    "likeCount": 12,
    "viewCount": 208
  }
];
